import type { Metadata } from "next";

import Header from "@/shared/Header";
import Footer from "@/shared/Footer";

export const metadata: Metadata = {
  title: "Exams Portal",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
