import type { Metadata } from "next";

import Header from "@/shared/Header";
import Footer from "@/shared/Footer";

export const metadata: Metadata = {
  title: "Exams Portal",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: string };
}) {
  return (
    <html lang="en">
      <body>
        <Header lng={lng} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
